def randomNumberGenerator(arg):
    """randomNumberGenerator
    Function: Generate a random sequence of length arg
    Why : it helps in changing the encryption scheme 
    Returns: a seq of random bits
   """
print(randomNumberGenerator.__doc__)


def form1b3():    
    """form1b3
    Parameters: it asks for plaintext and key
    Returns:returns a json object with the correct error message or the correct  ciphertext 
    """
print(form1b3.__doc__)


def form1b2():
    """form1b2
    Returns: A random seq of 8 bits for the next plaintext automatically generated by the computer
   """
print(form1b2.__doc__)

def form1b1():
    """form1b1
    Returns: A random seq of 8 bits for the next key automatically generated by the computer
   """
print(form1b1.__doc__)

def form1b4():
    """form1b4
    Returns:Changes the encryption scheme by calling randomNumberGenerator function
   """
print(form1b4.__doc__)

def form2b1():
    """form2b1
    returns: 256 pairs consiting of plaintext from 00000000 to 11111111 and their corresponding cipher text according to the given encryption scheme
    """
print(form2b1.__doc__)


def form4a():    
    """form4a
    Parameters: it asks for plaintext and key
    Returns:returns a json object with the correct error message or the correct  vernem ciphertext 
    """
print(form4a.__doc__)


def form4b():    
    """form4b
    Parameters: it asks for ciphertext and key
    Returns:returns a json object with the correct error message or the correct vernem plaintext 
    """
print(form4b.__doc__)

def form3():
    """form3
    Function: it asks the user if the given encryption scheme is correct 
    if the answer is yes then it asks for 2 plaintexts such that their corresponding cipher text is same
    if the cipher text is same then it displays correct answer
    while on the other hand it the encryption scheme is secure then the correct answer is when you type no

    """
print(form3.__doc__)

def check():
    """check
    if checks how many responses of the user are correct in the quiz
    """
print(check.__doc__)

def userfetch():
    """userfetch
    it helps in displaying the database
    """
print(userfetch.__doc__)
def addintext():
    """addintext
    It adds the plaintext in database
    """
print(addintext.__doc__)
def xor():
    """xor
    it does xor of two bits and help in calculating vernem cipher
    """
print(xor.__doc__)
def AND():
    """AND
    it does and of two bits and help in calculating the cipher for form 1 
    """
print(AND.__doc__)



